var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/imoveis/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__777b8fc7._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_7da4279f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7dd290df._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a3c12c32._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(public)_layout_tsx_742dd501._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_imoveis_[slug]_page_actions_345564c4.js")
R.m(37711)
module.exports=R.m(37711).exports
