var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/properties/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__49b10a40._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_ad83e40e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7dd290df._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a3c12c32._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_6e5a79cc._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_properties_[id]_page_actions_8160e558.js")
R.m(740133)
module.exports=R.m(740133).exports
